name: EZMC CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn clean package

    - name: Upload JAR to release
      if: github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: continuous
        name: Latest Build
        files: target/EZMC-*.jar
        prerelease: true
